trigger: none
pr: none

resources:
  pipelines:
  - pipeline: bicep-modules.Validate
    source: bicep-modules.Validate
    trigger:
      branches:
        include:
        - main

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

pool: 'Dedicated'

stages:
- stage: ValidateBicep
  jobs: 
  - job: PublishModules
    displayName: Publish Modules
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-bicep-modules'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $files = Get-ChildItem '$(Build.sourcesDirectory)/modules/*.bicep'

            foreach ($file in $files) {
              Write-Host "Publishing module '$($file.FullName)'"

              $fileShortName = $file.Name

              $publishName = $($fileShortName.Substring(0, $fileShortName.length - 6)).toLower()
              $publishTarget = "br:acrmxplatformprduksouth.azurecr.io/bicep/modules/$publishName:V$(Build.BuildId)"

              Write-Host "Publish target: '$publishTarget'"

              az bicep publish --file $file.FullName --target $publishTarget
            }
