trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: Build
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-Personal-Public-devtest'

stages:
- stage: Deploy
  jobs: 
  - job: PublishModules
    displayName: Publish Modules
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-bicep-modules'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $files = Get-ChildItem '$(Build.sourcesDirectory)/modules/*.bicep'

            foreach ($file in $files) {
              Write-Host "Publishing module '$($file.FullName)'"

              $fileShortName = $file.Name

              $publishName = $($fileShortName.Substring(0, $fileShortName.length - 6)).toLower()
              $dateForVersion = (Get-Date).ToString("yyyy.MM.dd")
              $publishTarget = "br:acrmxplatformprduksouth.azurecr.io/bicep/modules/$($publishName):V$dateForVersion.$(Build.BuildId)"

              Write-Host "Publish target: '$publishTarget'"

              az bicep publish --file $file.FullName --target $publishTarget
            }
