trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  autoCancel: false
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: Build
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-bicep-modules-production'
      bicepDirectory: '$(Build.sourcesDirectory)/modules'
      
- stage: Deploy
  jobs: 
  - job: PublishModules
    displayName: Publish Modules
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'spn-bicep-modules-production'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          inlineScript: |
            # Set the release to be a preview release unless the branch is main
            $previewRelease = $true
            $sourceBranch = "${env:BUILD_SOURCEBRANCH}"
            Write-Host "Branch name: '$sourceBranch'"
            if ($sourceBranch -eq 'refs/heads/main') { $previewRelease = $false }

            # Get all of the module folders
            $folders = Get-ChildItem "${env:BUILD_SOURCESDIRECTORY}/modules"

            # Loop through all of the bicep modules and call the publish script
            foreach ($folder in $folders) {
              $moduleName = $folder.Name.ToLower()

              . ${env:BUILD_SOURCESDIRECTORY}/.azure-pipelines/scripts/Publish-BicepModuleToAcr.ps1 `
                -moduleName $moduleName `
                -modulesRootPath ${env:BUILD_SOURCESDIRECTORY}/modules `
                -acrName acrty7og2i6qpv3s `
                -previewRelease $previewRelease
            }
