trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: Build
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-Personal-Public-devtest'
      bicepDirectory: '$(Build.sourcesDirectory)/modules'
      
- stage: Deploy
  jobs: 
  - job: PublishModules
    displayName: Publish Modules
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-bicep-modules'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Set the release to be a preview release unless the branch is main
            $previewRelease = $true
            $sourceBranch = "${env:BUILD_SOURCEBRANCH}"
            Write-Host "Branch name: '$sourceBranch'"
            if ($sourceBranch -eq 'refs/heads/main') { $previewRelease = $false }

            # Get all of the *.bicep files in the modules folder
            $files = Get-ChildItem '${env:BUILD.SOURCESDIRECTORY}/modules/*.bicep'

            # Loop through all of the bicep modules and call the publish script
            foreach ($file in $files) {
              $moduleName = $($file.Name.Substring(0, $file.Name.Length - 6)).ToLower()

              . ${env:BUILD.SOURCESDIRECTORY}/.azure-pipelines/scripts/Publish-BicepModuleToAcr.ps1 `
                -moduleName $moduleName `
                -modulesRootPath ${env:BUILD.SOURCESDIRECTORY}/modules `
                -metadataRootPath ${env:BUILD.SOURCESDIRECTORY}/metadata `
                -acrName acrmxplatformprduksouth `
                -previewRelease $previewRelease
            }
