trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: Build
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-Personal-Public-devtest'
      bicepDirectory: '$(Build.sourcesDirectory)/modules'
      
- stage: Deploy
  jobs: 
  - job: PublishModules
    displayName: Publish Modules
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-bicep-modules'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Set the release to be a preview release unless the branch is main
            $previewRelease = $true
            $sourceBranchName = $(Build.SourceBranchName)
            if ($sourceBranchName -eq 'main') { $previewRelease = $false }

            # Get all of the *.bicep files in the modules folder
            $files = Get-ChildItem '$(Build.sourcesDirectory)/modules/*.bicep'

            # Loop through all of the bicep modules and call the publish script
            foreach ($file in $files) {
              $moduleName = $($file.Name.Substring(0, $file.Name.Length - 6)).ToLower()

              . $(Build.sourcesDirectory)/.azure-pipelines/scripts/Publish-BicepModuleToAcr.ps1 `
                -moduleName $moduleName `
                -modulesRootPath $(Build.sourcesDirectory)/modules `
                -metadataRootPath $(Build.sourcesDirectory)/metadata `
                -acrName acrmxplatformprduksouth `
                -previewRelease $previewRelease
            }
